package com.ricky.adocao.enums

enum class PetCidadeEnum {
    CEILANDIA,
    SAMAMBAIA,
    PLANO_PILOTO,
    TAGUATINGA,
    PLANALTINA,
    GUARA_1,
    GUARA_2,
    GAMA,
    RECANTO_DAS_EMAS,
    SANTA_MARIA,
    AGUAS_CLARAS,
    SAO_SEBASTIAO,
    RIACHO_FUNTO_2,
    SOL_NASCENTE,
    SOBRADINHO_2,
    SOBRADINHO,
    VINCENTE_PIRES,
    PARANOA,
    ITAPOA,
    SUDOESTE,
    OCTOGONAL,
    BRAZLANDIA,
    JARDIM_BOTANICO,
    RIACHO_FUNDO,
    ARNIQUEIRA,
    LAGO_NORTE,
    SCIA,
    CRUZEIRO_NOVO,
    CRUZEIRO_VELHO,
    LAGO_SUL,
    NOROESTE,
    NUCLEO_BANDEIRANTE,
    PARK_WAY,
    CANDANGOLANDIA,
    VARJAO,
    FERCAL,
    SIA;

    override fun toString(): String {
        return when (this) {
            CEILANDIA -> "PET_CIDADE_CEILANDIA"
            SAMAMBAIA -> "PET_CIDADE_SAMAMBAIA"
            PLANO_PILOTO -> "PET_CIDADE_PLANO_PILOTO"
            TAGUATINGA -> "PET_CIDADE_TAGUATINGA"
            PLANALTINA -> "PET_CIDADE_PLANALTINA"
            GUARA_1 -> "PET_CIDADE_GUARA_1"
            GUARA_2 -> "PET_CIDADE_GUARA_2"
            GAMA -> "PET_CIDADE_GAMA"
            RECANTO_DAS_EMAS -> "PET_CIDADE_RECANTO_DAS_EMAS"
            SANTA_MARIA -> "PET_CIDADE_SANTA_MARIA"
            AGUAS_CLARAS -> "PET_CIDADE_AGUAS_CLARAS"
            SAO_SEBASTIAO -> "PET_CIDADE_SAO_SEBASTIAO"
            RIACHO_FUNTO_2 -> "PET_CIDADE_RIACHO_FUNTO_2"
            SOL_NASCENTE -> "PET_CIDADE_SOL_NASCENTE"
            SOBRADINHO_2 -> "PET_CIDADE_SOBRADINHO_2"
            SOBRADINHO -> "PET_CIDADE_SOBRADINHO"
            VINCENTE_PIRES -> "PET_CIDADE_VINCENTE_PIRES"
            PARANOA -> "PET_CIDADE_PARANOA"
            ITAPOA -> "PET_CIDADE_ITAPOA"
            SUDOESTE -> "PET_CIDADE_SUDOESTE"
            OCTOGONAL -> "PET_CIDADE_OCTOGONAL"
            BRAZLANDIA -> "PET_CIDADE_BRAZLANDIA"
            JARDIM_BOTANICO -> "PET_CIDADE_JARDIM_BOTANICO"
            RIACHO_FUNDO -> "PET_CIDADE_RIACHO_FUNDO"
            ARNIQUEIRA -> "PET_CIDADE_ARNIQUEIRA"
            LAGO_NORTE -> "PET_CIDADE_LAGO_NORTE"
            SCIA -> "PET_CIDADE_SCIA"
            CRUZEIRO_NOVO -> "PET_CIDADE_CRUZEIRO_NOVO"
            CRUZEIRO_VELHO -> "PET_CIDADE_CRUZEIRO_VELHO"
            LAGO_SUL -> "PET_CIDADE_LAGO_SUL"
            NOROESTE -> "PET_CIDADE_NOROESTE"
            NUCLEO_BANDEIRANTE -> "PET_CIDADE_NUCLEO_BANDEIRANTE"
            PARK_WAY -> "PET_CIDADE_PARK_WAY"
            CANDANGOLANDIA -> "PET_CIDADE_CANDANGOLANDIA"
            VARJAO -> "PET_CIDADE_VARJAO"
            FERCAL -> "PET_CIDADE_FERCAL"
            SIA -> "PET_CIDADE_SIA"
        }
    }
}