package com.ricky.adocaoapp.domain.enums

enum class PetCidadeEnum(override val value: String) : EnumWithValue {
    AGUAS_CLARAS("Águas Claras"),
    ARNIQUEIRA("Arniqueiras"),
    BRAZLANDIA("Brazlandia"),
    CANDANGOLANDIA("Candangolândia"),
    CEILANDIA("Ceilância"),
    CRUZEIRO_NOVO("Cruzeiro Novo"),
    CRUZEIRO_VELHO("Cruzeiro Velho"),
    FERCAL("Fercal"),
    GAMA("Gama"),
    GUARA_1("Guará 1"),
    GUARA_2("Guará 2"),
    ITAPOA("Itapoã"),
    JARDIM_BOTANICO("Jardim Botânico"),
    LAGO_NORTE("Lago Norte"),
    LAGO_SUL("Lago Sul"),
    NOROESTE("Noroeste"),
    NUCLEO_BANDEIRANTE("Núcleo Bandeirante"),
    OCTOGONAL("Octogonal"),
    PARANOA("Paranoá"),
    PARK_WAY("Park Way"),
    PLANALTINA("Planaltina"),
    PLANO_PILOTO("Plano Piloto"),
    RECANTO_DAS_EMAS("Recanto das Emas"),
    RIACHO_FUNDO("Riacho Fundo"),
    RIACHO_FUNTO_2("Riacho Fundo 2"),
    SAMAMBAIA("Samambaia"),
    SANTA_MARIA("Santa Maria"),
    SAO_SEBASTIAO("São Sebastião"),
    SCIA("SCIA"),
    SIA("SIA"),
    SOBRADINHO("Sobradinho"),
    SOBRADINHO_2("Sobradinho 2"),
    SOL_NASCENTE("Sol Nascente"),
    SUDOESTE("Sudoeste"),
    TAGUATINGA("Taguatinga"),
    VARJAO("Varjão"),
    VINCENTE_PIRES("Vicente Pires");
}