spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3308/adocao_db?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'
  error:
    include-stacktrace: never