CREATE TABLE USUARIO_ROLE(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` VARCHAR(255) NOT NULL,
    `ROLE_ID` INTEGER NOT NULL,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`USER_ID`) REFERENCES `USUARIO` (`USER_ID`),
    FOREIGN KEY(`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`)
);