version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adocao_db

volumes:
  dbbase:

#docker-compose -f mysql-docker-compose.yml up -d