CREATE TABLE ROLE(
    `ROLE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ROLE_ID`)
);

    INSERT INTO `ROLE` (`ROLE_ID`, `NOME`) VALUES (1, 'ADMIN')
    INSERT INTO `ROLE` (`ROLE_ID`, `NOME`) VALUES (2, 'USER')