CREATE TABLE USUARIO_ROLE(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ROLE_ID` BIGINT NOT NULL,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`USER_ID`) REFERENCES `USUARIO` (`USER_ID`),
    FOREIGN KEY(`ROLE_ID`) REFERENCES `ROLE_ID` (`ROLE_ID`)
);
